import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Header from '@/app/components/Header/Header';
import Sidebar from '@/app/components/Sidebar/Sidebar';
import { SidebarProvider } from '@/app/components/Sidebar/context';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Test Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SidebarProvider>
          <Header />
          <main className="md:grid bg-white dark:bg-neutral-950 mt-14 gap-2 min-h-screen">
            <Sidebar />
            <div className="flex md:mr-[250px]" style={{ gridArea: 'main' }}>
              {children}
            </div>
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
